title: WWT Contributor Hub
url: "https://worldwidetelescope.github.io"
email: wwt@aas.org
description: >-
  The hub for people who want to contribute to the AAS WorldWide
  Telescope project.
twitter_username: wwtelescope
github_username: WorldWideTelescope
remote_theme: pmarsceill/just-the-docs

logo: "stacked-logo.png"

aux_links:
  "Source on GitHub!":
    - "//github.com/WorldWideTelescope/worldwidetelescope.github.io/"

footer_content: "Copyright 2019-2020 the .NET Foundation. The AAS WorldWide Telescope is brought to you by the American Astronomical Society <a href=\"/#acknowledgments\">and other supporters</a>."

ga_tracking: UA-107473046-4

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
