title: WWT Contributor Hub
url: "https://worldwidetelescope.github.io"
email: wwt@aas.org
description: >-
  The hub for resources related to contributions to the AAS WorldWide
  Telescope project.
twitter_username: wwtelescope
github_username: WorldWideTelescope
remote_theme: pmarsceill/just-the-docs

aux_links:
  "View on GitHub!":
    - "//github.com/WorldWideTelescope/worldwidetelescope.github.io/"

ga_tracking: UA-107473046-4

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
